#version: '3.8'
#services:
#  postgres:
#    image: postgres:15.4
#    container_name: postgres-container
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: security
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#volumes:
#  postgres_data:

version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data1:/data/db
    environment:
      MONGO_INITDB_DATABASE: productsdb2

volumes:
  mongo_data1:
